### PR TITLE
Add container support using Docker

### PR DESCRIPTION
**Pull request by DannyvdSluijs**
This pull request adds container support using docker. 
It uses Nginx and PHP5-fpm. 

The web interface is exposed over port 8080 (http://localhost:8080) and the gitlist sources are mounted as the application folder and under `/repos/gitlist`. Using `/repos` in your config.ini should display the sources with gitlist.

### CODE REVIEW

**Comment by alehaa** [comment]
Honestly, I'm not sure to put a docker config into the official repo. The intention of GitList is afaik to keep it as simple as possible. By merging this PR we would officially support docker. Someone would have to test and maintain it, etc.

I would prefer to put these files into a separate repository if docker supports this, or alternatively merge into a separate branch.

**Comment by PABourdin** [comment]
I agree: We are not promoting third-party products.
The docker-configuration could be explained later in the documentation or in a "contrib" folder.

**Comment by DannyvdSluijs** [comment]
@alehaa I believe phpstan is a project which has done it as you are suggesting. There is phpstan/phpstan the main repo, and there is phpstan/docker-image (See https://github.com/phpstan/docker-image). The approach is different as is is a single container, where is I've done a composition of two containers (NGINX and PHP). I guess we could replace the NGINX webserver with the builtin PHP webserver (```php -S 0.0.0.0:8080```) and have a single container running. When I have some time to look into this I will give it a go. 

Lets close the PR for now and aim for an external repo. I'll keep the feature-docker branch alive in my fork for future referencing.

**Comment by alehaa** [comment]
Afaik the builtin PHP webserver isn't meant to be used in production.

**Comment by alehaa** [comment]
@DannyvdSluijs Have you already seen the repository linked in the wiki?

https://github.com/davibe/gitlist-docker

**Pull request closed without merging**
