### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by PABourdin**
index.php is pretty url.

### CODE REVIEW

**Comment by PABourdin** [comment]
I do no really understand, why git complains "This branch is out-of-date with the base branch", because this file was untouched in my previous commits. So this change should be able to be merged automatically...

Furthermore, the proposed method for resolution would require write access to akashima/gitlist, no?
I do not have write permission there... what should I do?

**Comment by alehaa** [comment]
As GitHub proposed: Your branch is not merged with the latest master. I've enabled branch-protection for this repo, ensuring a) your branch is in sync with the current master and b) the tests of the resulting branch succeed. In addition your fork is from the original GitList, not this fork.

How to fix this:
```shell
git clone https://github.com/akashima/gitlist.git
cd gitlist
git checkout htaccess
git remote add gitlist-php https://github.com/gitlist-php/gitlist.git
git fetch gitlist-php
git merge gitlist-php/master
git push gitlist-php
```

**Comment by PABourdin** [comment]
Got it... Edit: *works* now, Thanks!

**Comment by alehaa** [comment]
Moved to `tmp` branch, as not authorized for `master` yet. Removed `duplicate` tag, as this is the original PR.

**Pull request merged**
