### PR TITLE
Feature/silex2

### PR DESCRIPTION
**Pull request by PABourdin**
Migration to Silex 2 and Symphony 2.8, please review.

### CODE REVIEW

**Comment by alehaa** [comment]
I believe some of the changes belong to other pull requests or forks (see #7), e.g. 

```diff
-    public function getHead()
+    public function getHead($default = NULL)
```

I will check this PR after merging the other orphan forks. Thanks @PABourdin! ;)

**Comment by PABourdin** [comment]
@alehaa Yes, there is another branch with only this change. Nonetheless, I wanted to fix this already during the Silex 2 migration because of a relatively clear warning (PHP notice). You may of course first pull in the other branch, followed by this PR, if you like. There should not arise a conflict, I hope.

**Comment by PABourdin** [comment]
The feature/silex2 branch can be deleted now, I guess? Or do you want to keep it?
Thanks @alehaa

**Comment by alehaa** [comment]
Done.

**Pull request merged**
