### PR TITLE
fix: issue #14

### PR DESCRIPTION
**Pull request by E-t-z**
Apache 2.4 needs a bit different .htaccess

This fix is untested on Apache 2.2

### CODE REVIEW

**Comment by E-t-z** [comment]
Probably works fine on Apache 2.2, but it would be better if someone can test it.

**Comment by E-t-z** [comment]
Will submit proper fix.

Obviously this was not the file, I actually wanted to submit.

**Comment by alehaa** [comment]
Little advice: You can always overwrite your PR by adding more commits or force-pushing alternative ones to the branch of the PR.

**Comment by E-t-z** [comment]
Well, not so easy when doing stuff via Smartphone and Github web. ;)
But you are right.

**Pull request closed without merging**
