### PR TITLE
Improving test coverage

### PR DESCRIPTION
**Pull request by DannyvdSluijs**
As mentioned this:

- Adds vfsStream as a require-dev to easier mock any file system interactions
- Adds a specific bootstrap script for testing, currently setting UTC timezone
- Adds a test for Config class
- Corrects scope usage in InterfaceTest

### CODE REVIEW

**Comment by alehaa** [comment]
@DannyvdSluijs please open a separate PR for the docker config if this hasn't been pushed by mistake. One PR per feature ;)

You can remove the commit from this PR by resetting the branch to `HEAD^` and force-pushing to your branch at origin.

**Comment by DannyvdSluijs** [comment]
Yes this was accidental. Didn't realize an extra commit would automatically be added to the same pull request without any action from my side 

Can I do multiple streams of features by means of an additional (feature) branch? And making pull requests from the feature branch into gitlist-php master branch?

**Comment by alehaa** [comment]
Indeed. Create a separate branch foreach feature and open a PR when the feature is finished. However - if the features are related one can put them in one PR (e.g. changing from A to B in classes X,Y,Z may be in one PR instead of three - "Porting to Silex 2" and "Added nginx config" are two separate PR).

**Comment by DannyvdSluijs** [comment]
@alehaa did as you mentioned. Thanks for the comprehensive guide this made it easy.

**Pull request merged**
